cv_folds: 3
data_folder: ./analyzed_data  # Changed from ../raw_data
drift_threshold: 0.1
model_registry_path: ./model_registry
models:
  DecisionTree:
    class_weight:
    - balanced
    max_depth:
    - 10
    - 15
    min_samples_leaf:
    - 2
    - 4
    min_samples_split:
    - 5
    - 10
  NeuralNetwork:
    alpha:
    - 0.001
    - 0.01
    hidden_layer_sizes:
    - - 100
    - - 100
      - 50
    learning_rate_init:
    - 0.001
  RandomForest:
    class_weight:
    - balanced
    max_depth:
    - 10
    min_samples_leaf:
    - 2
    - 4
    min_samples_split:
    - 10
    n_estimators:
    - 100
    - 200
random_state: 42
test_size: 0.2
use_class_weight: true
